allowed-duplicate-crates = [
    "bitflags",
    "embedded-io",
    "getrandom",
    "icu_collections",
    "icu_properties",
    "icu_properties_data",
    "icu_provider",
    "kurbo",
    "litemap",
    "png",
    "serde_spanned",
    "tinystr",
    "toml",
    "toml_datetime",
    "ureq",
    "windows-sys",
    "windows-targets",
    "windows_aarch64_gnullvm",
    "windows_aarch64_msvc",
    "windows_i686_gnu",
    "windows_i686_gnullvm",
    "windows_i686_msvc",
    "windows_x86_64_gnu",
    "windows_x86_64_gnullvm",
    "windows_x86_64_msvc",
    "writeable",
    "yoke",
    "yoke-derive",
    "zerotrie",
    "zerovec",
    "zerovec-derive",
]